#!/bin/sh
# Try to use system OpenSSL includes if present (Homebrew on macOS)
OPENSSL_INCLUDE=${OPENSSL_INCLUDE:-"-I/usr/local/opt/openssl/include -I/opt/homebrew/opt/openssl/include"}
OPENSSL_LIBS=${OPENSSL_LIBS:-"-L/usr/local/opt/openssl/lib -L/opt/homebrew/opt/openssl/lib -lcrypto"}

gcc -O3 -march=native -mtune=native -Wall -Wextra -Wno-unused-function -Wno-unused-parameter -Wno-sign-compare \
  -I. -Isubroutines -I.. -I../src \
  -DKAT -DKATNUM=`cat KATNUM` "-DCRYPTO_NAMESPACE(x)=x" "-D_CRYPTO_NAMESPACE(x)=_##x" \
  $OPENSSL_INCLUDE \
  -o kat \
  nist/kat_kem.c nist/rng.c benes.c bm.c controlbits.c decrypt.c encrypt.c gf.c operations.c pk_gen.c root.c sk_gen.c synd.c transpose.c util.c \
  ../src/mceliece_shake.c \
  $OPENSSL_LIBS -ldl 
